CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Clientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "DniCuit" character varying(20) NOT NULL,
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

CREATE TABLE "Proveedores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RazonSocial" character varying(150) NOT NULL,
    "Contacto" character varying(100),
    CONSTRAINT "PK_Proveedores" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Rol" text NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Productos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" character varying(100) NOT NULL,
    "Descripcion" character varying(100) NOT NULL,
    "Precio" numeric(18,2) NOT NULL,
    "StockActual" integer NOT NULL,
    "ImagenUrl" character varying(255),
    "CategoriaId" integer NOT NULL,
    CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Productos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IngresosProductos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fecha" timestamp with time zone NOT NULL,
    "Cantidad" integer NOT NULL,
    "ProveedorId" integer NOT NULL,
    "ProductoId" integer NOT NULL,
    CONSTRAINT "PK_IngresosProductos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IngresosProductos_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IngresosProductos_Proveedores_ProveedorId" FOREIGN KEY ("ProveedorId") REFERENCES "Proveedores" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SalidasProductos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Fecha" timestamp with time zone NOT NULL,
    "Cantidad" integer NOT NULL,
    "ClienteId" integer NOT NULL,
    "ProductoId" integer NOT NULL,
    CONSTRAINT "PK_SalidasProductos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SalidasProductos_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SalidasProductos_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_IngresosProductos_ProductoId" ON "IngresosProductos" ("ProductoId");

CREATE INDEX "IX_IngresosProductos_ProveedorId" ON "IngresosProductos" ("ProveedorId");

CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");

CREATE INDEX "IX_SalidasProductos_ClienteId" ON "SalidasProductos" ("ClienteId");

CREATE INDEX "IX_SalidasProductos_ProductoId" ON "SalidasProductos" ("ProductoId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908142741_InicializacionDB', '8.0.30');

COMMIT;

START TRANSACTION;

ALTER TABLE "SalidasProductos" RENAME COLUMN "Fecha" TO "FechaRegistro";

ALTER TABLE "Productos" RENAME COLUMN "StockActual" TO "Stock";

ALTER TABLE "IngresosProductos" RENAME COLUMN "Fecha" TO "FechaRegistro";

ALTER TABLE "Productos" ALTER COLUMN "Nombre" TYPE text;

ALTER TABLE "Productos" ALTER COLUMN "ImagenUrl" TYPE text;

ALTER TABLE "Productos" ALTER COLUMN "Descripcion" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908202958_AjusteAnotaciones', '8.0.30');

COMMIT;

